### ISSUE TITLE
Host change - causes trouble with development

### ISSUE THREAD

**Issue by pndpo** [MichaelFlops/omari#15]
Can't serve this locally. Dunno what's up.

**Comment by cmehrabian** [comment]
bower install
sudo npm install
grunt serve  

worked for me, but keep me posted on what you think is up

**Comment by MichaelFlops** [comment]
I fixed it- it was an issue in the gruntfile.js (sorry I changed the hostname when messing with the server)

**Comment by MichaelFlops** [comment]
to get to working now simply run it at 0.0.0.0/9005
